### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by schmoelder** [wilson-ye-chen/stein_thinning#1]
Hi,

I've heard about this package from a colleague and we like it! :nerd_face:

Have you considered publishing it to PyPI? It would be very beneficial to install and manage the package using package managers like pip. By making it available on PyPI, you would make using your package much easier for new users.
Additionally, PyPI provides versioning support, making it convenient for users to update to newer releases seamlessly. 

If you need any assistance with the publishing process or have any questions, feel free to reach out!

Best regards

**Comment by aglebov** [comment]
@schmoelder in case you are still interested, the package is now available on PyPI:
https://pypi.org/project/stein-thinning/
